/*bg:TPL_COMMENT [TEMPLATE_FILE: "lib.tpl.rs"]*/
//***
//* This file is generated by bindgen.red from lib.tpl.rs
//*** /*bg-end:TPL_COMMENT*/

use std::ffi::{CString, c_char};
use std::time::Duration;
use std::collections::BTreeSet;
use std::path::PathBuf;
use bytes::Bytes;
use tokio::runtime::Runtime;
use bls::SecretKey;
use libp2p::Multiaddr;
use xor_name::XorName;
use sn_registers::{RegisterAddress, EntryHash};
use sn_protocol::NetworkAddress;
use sn_protocol::storage::ChunkAddress;
use sn_transfers::{NanoTokens, MainPubkey, CashNote, UniquePubkey, client_transfers::{TransferOutputs, SpendRequest}};
use redbin::{de::from_bytes as from_redbin, ser::to_bytes as to_redbin};
use serde::Serialize;

/*bg:API_IMPORT [MOD:"sn_api::" NAME: "Safe"]*/
use sn_api::Safe;/*bg-end:API_IMPORT*/


#[repr(C)]
pub struct Buffer {
	data: *mut u8,
	len: usize,
}

#[derive(Serialize)]
struct ErrorString(String, String);

/*bg:OBJ_DEFAULT [
    NAME: "Safe"
    LOWNAME: "s_afe"
]*/
#[no_mangle]
pub extern "C" fn s_afe_default() -> *mut Safe {
    Box::into_raw(Box::new(Safe::default()))
}

#[no_mangle]
pub extern "C" fn s_afe_free(ptr: *mut Safe) {
    if ptr.is_null() {
        return;
    }
    unsafe {
        Box::from_raw(ptr);
    }
}
/*bg-end:OBJ_DEFAULT*/


/*bg:FIELD_STRING [
    NAME: "Safe"
    LOWNAME: "s_afe"
    FIELDNAME: "xorurl_base"
]*/
#[no_mangle]
pub extern "C" fn s_afe_xorurl_base(ptr: *const Safe) -> *mut c_char {
    assert!(!ptr.is_null());
    let s_afe = unsafe {
        &*ptr
    };

    let xorurl_base = CString::new(s_afe.xorurl_base.to_string()).expect("Could not convert to CString");
    xorurl_base.into_raw()
}
/*bg-end:FIELD_STRING*/


/*bg:METHOD [
    NAME: "Safe"
    LOWNAME: "s_afe"
    METHODNAME: "connect"
    RETURN: "Result<(), Error>"
]*/
#[no_mangle]
pub extern "C" fn s_afe_connect(rt_ptr: *mut Runtime, /*bg:s_afe_connect_SELF []*/s_afe_ptr: *mut Safe, /*bg-end:s_afe_connect_SELF*/params: *const u8, params_size: usize) -> Buffer {
    println!("s_afe_connect pointer: {:?}, size: {:?}", params, params_size);

    /*bg:s_afe_connect_SELF []*/assert!(!s_afe_ptr.is_null());/*bg-end:s_afe_connect_SELF*/
    assert!(!rt_ptr.is_null());
    
    let params: &[u8] = unsafe { std::slice::from_raw_parts(params, params_size) };
    println!("s_afe_connect u8: {:?}", params);

    let params: (
    /*bg:s_afe_connect_PARAM [
        PARAMNAME: "app_keypair"
        PARAMTYPE: "Option<Keypair>"
    ]*/
        Option<Keypair>, // app_keypair /*bg-end:s_afe_connect_PARAM*/
    ) = from_redbin(params).unwrap();
    println!("s_afe_connect params: {:?}", params);

    let ret = unsafe { // Result<(), Error>
        /*bg:s_afe_connect_SELF []*/let s_afe = &mut *s_afe_ptr;/*bg-end:s_afe_connect_SELF*/
        let rt = &mut *rt_ptr;
        rt.block_on(Safe::connect(/*bg:s_afe_connect_SELF []*/s_afe/*bg-end:s_afe_connect_SELF*//*bg:s_afe_connect_PARAM [PARAMNUM: "0" COMMA: ", " BORROW: "&"]*/, &params.0/*bg-end:s_afe_connect_PARAM*/))
    };
    let ret = ret.map_err(|err| ErrorString(format!("{:?}", err), format!("{}", err)));
    /*bg:s_afe_connect_RETURN_REF []*/
    let ret: Result<usize, ErrorString> = ret.map(|value| Box::into_raw(Box::new(value)) as usize);
    /*bg-end:s_afe_connect_RETURN_REF*/
	let mut ret_bytes: Vec<u8> = to_redbin(&ret).unwrap();
	let data = ret_bytes.as_mut_ptr();
	let len = ret_bytes.len();
	std::mem::forget(ret_bytes);
	return Buffer { data, len };
}
/*bg-end:METHOD*/

#[no_mangle]
pub extern "C" fn init_runtime() -> *mut Runtime {
    Box::into_raw(Box::new(Runtime::new().unwrap()))
}

#[no_mangle]
pub extern "C" fn cstring_free(cstring: *mut c_char) {
    if cstring.is_null() {
        return;
    }
    unsafe {
        CString::from_raw(cstring);
    }
}

#[no_mangle]
pub extern "C" fn buffer_free(buf: Buffer) {
	let b: &mut [u8] = unsafe { std::slice::from_raw_parts_mut(buf.data, buf.len) };
	unsafe {
		Box::from_raw(b.as_mut_ptr());
	}
}
