[package]
name = "sn_ffi"
version = "0.1.0"
authors = ["loziniak <maciej@robotix-lozinski.pl>"]
edition = "2018"

[dependencies]
sn_api = { git = "https://github.com/loziniak/sn_api", branch = "sn-ffi" }

[lib]
name = "sn_ffi"
crate-type = ["cdylib"]
